# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b7f7fdaac48620451f65833ba29b2fbe20161e780ad602ac41bf2bff4c54dea895ec9342de1270e3cbfcc736af6c71f5cc1732dc2dae119f7291bdc11234f26

test:
  secret_key_base: 1b6cae47ae34743e4928900e65c13dfba5e10d0a60795466400ad85c1ec927172659d33b50fbf1f7a56f5b125952050814d831d32fd7ba516b354eb36afc2851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
